### ISSUE TITLE
Pset Guide: Module 3

### ISSUE THREAD

**Issue by jesseilev** [LaunchCodeEducation/cs50x-live#16]
<a href="https://github.com/jesseilev"><img src="https://avatars.githubusercontent.com/u/4194941?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jesseilev](https://github.com/jesseilev)**
_Friday Dec 11, 2015 at 00:39 GMT_
_Originally opened as https://github.com/Launch-Code/cs50x-live-2016/issues/70_

---

See [here](https://github.com/LaunchCodeEducation/cs50x-live-2016/tree/feature/module3/calendar/cs50/unit1-fundamentals/module3/materials/problem-set)

**Comment by jesseilev** [comment]
<a href="https://github.com/leanne63"><img src="https://avatars.githubusercontent.com/u/7043045?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [leanne63](https://github.com/leanne63)**
_Thursday Dec 17, 2015 at 23:21 GMT_

---

Done

**Comment by newjoiner** [comment]
@jesseilev 

The videos were too old.
~~I found some other videos that may help the students.  They are from 2013, but are listed under the fall 2015 walkthrough problem set section of cs50.tv <a href="http://cs50.tv/2015/fall/#about,walkthroughs" target="_blank">here</a>~~

~~List of Walkthroughs
1. <a href="https://www.youtube.com/watch?v=CvmHt-IDhbs" target="_blank">fifteen</a>
2. <a href="https://www.youtube.com/watch?v=k4P0SojW9oM" target="_blank">fifteen / draw</a>
3. <a href="https://www.youtube.com/watch?v=xPa4Wb5Uyhc" target="_blank">fifteen / init</a>
4. <a href="https://www.youtube.com/watch?v=gxMHcoBMiq4" target="_blank">fifteen / move</a>
5. <a href="https://www.youtube.com/watch?v=6KSq4JUfhIk" target="_blank">fifteen / won</a>~~

**Comment by jesseilev** [comment]
@newjoiner nice find. Are these definitely too old? If it's just a matter of IDE vs Appliance or something, the students might still benefit from watching them

**Comment by newjoiner** [comment]
@jesseilev The videos were from 2013 but still seem to be useful.  They still have to implement the same methods (draw, init, move, and won) in the pset and still appear to be relevant.

BTW - the generate.c file for find has some TODOs for adding comments.  I don't see it as part of the submission process, so if it's not important you can skip this.

**Comment by jesseilev** [comment]
Nice, I added them in.
